name: the_movies_api
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.0.3 # https://pub.dev/packages/bloc
  cupertino_icons: ^1.0.2 # https://pub.dev/packages/cupertino_icons
  dartz: ^0.10.1 # https://pub.dev/packages/dartz
  equatable: ^2.0.3 # https://pub.dev/packages/equatable
  flutter_bloc: ^8.0.1 # https://pub.dev/packages/flutter_bloc
  flutter_rating_stars: ^1.1.0 # https://pub.dev/packages/flutter_rating_stars
  get_it: ^7.2.0 # https://pub.dev/packages/get_it
  go_router: ^13.2.3 # https://pub.dev/packages/go_router
  golden_toolkit: ^0.15.0 # https://pub.dev/packages/golden_toolkit
  http: ^0.13.4 # https://pub.dev/packages/http
  intl: ^0.19.0 # https://pub.dev/packages/intl
  lottie: ^3.0.0 # https://pub.dev/packages/lottie
  percent_indicator: any # https://pub.dev/packages/percent_indicator
  shimmer: ^3.0.0 # https://pub.dev/packages/shimmer
  dartdoc: ^8.0.8 # https://pub.dev/packages/dartdoc
  configcat_client: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^0.3.0
  bloc_test: ^9.0.3
  flutter_lints: ^1.0.0
  network_image_mock: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/core/assets/images/
    - lib/core/assets/animation/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
